#!/bin/bash
# ABOUTME: Builds + ad-hoc-signs Tapedeck.app for local testing. No DMG, no notarisation.
# ABOUTME: Skips keychain-access-groups entitlement (needs provisioning profile for that);
# ABOUTME: KeychainStore detects the missing entitlement at runtime and uses the legacy
# ABOUTME: file-based keychain — which same-user processes share automatically.

set -euo pipefail

PROJECT="Tapedeck.xcodeproj"
SCHEME="Tapedeck"
BUILD_DIR="./build/local"
DD_PATH="$BUILD_DIR/DerivedData"
APP_OUT="$BUILD_DIR/Tapedeck.app"

rm -rf "$BUILD_DIR"
xcodegen generate

# Strip keychain-access-groups so unsigned/ad-hoc-signed builds don't trip over the
# missing provisioning profile. Regenerated by xcodegen each run, so safe to mutate.
/usr/libexec/PlistBuddy -c "Delete :keychain-access-groups" Tapedeck/Tapedeck.entitlements 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Delete :keychain-access-groups" TapedeckSyncHelper/TapedeckSyncHelper.entitlements 2>/dev/null || true

echo "==> Building (ad-hoc signed)..."
xcodebuild -project "$PROJECT" \
  -scheme "$SCHEME" \
  -configuration Debug \
  -derivedDataPath "$DD_PATH" \
  CODE_SIGN_IDENTITY="-" \
  CODE_SIGN_STYLE=Manual \
  DEVELOPMENT_TEAM="" \
  PROVISIONING_PROFILE_SPECIFIER="" \
  ENABLE_HARDENED_RUNTIME=NO \
  build \
  -quiet

mkdir -p "$BUILD_DIR"
rm -rf "$APP_OUT"
cp -R "$DD_PATH/Build/Products/Debug/Tapedeck.app" "$APP_OUT"

echo ""
echo "==> Built $APP_OUT"
echo "    Launch with: open $APP_OUT"
echo "    Logs at:     tail -F ~/Library/Logs/Tapedeck/sync.log"
echo "    State at:    ~/Library/Application\\ Support/Tapedeck/state.db"
echo ""
echo "Note: ad-hoc signing means keychain-access-groups is disabled — the UI and"
echo "helper share secrets via the legacy login keychain instead. Release builds"
echo "go through scripts/build-release.sh and use the data-protection keychain."
